name: Automate Snapchat Posting

on:
  push:
    branches:
      - main

jobs:
  post-to-snapchat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Snapchat automation script
        env:
          SNAPCHAT_USERNAME: ${{ secrets.SNAPCHAT_USERNAME }}
          SNAPCHAT_PASSWORD: ${{ secrets.SNAPCHAT_PASSWORD }}
        run: |
          python automate_snapchat.py
